// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTothW3PGUrMdeChwfpHuLFVe23959l0g',
    appId: '1:521390409536:web:c228684e8a8edacbf39ca5',
    messagingSenderId: '521390409536',
    projectId: 'ipssiflutter-4fee9',
    authDomain: 'ipssiflutter-4fee9.firebaseapp.com',
    storageBucket: 'ipssiflutter-4fee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxXzH5J5goxhOC2JgLoPKvhAkCsuCAq0E',
    appId: '1:521390409536:android:4c0e97271a245daef39ca5',
    messagingSenderId: '521390409536',
    projectId: 'ipssiflutter-4fee9',
    storageBucket: 'ipssiflutter-4fee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KCOw2lAXKrS9LTw8VZrdYEWLH0yACmI',
    appId: '1:521390409536:ios:e95d0d36de0ac935f39ca5',
    messagingSenderId: '521390409536',
    projectId: 'ipssiflutter-4fee9',
    storageBucket: 'ipssiflutter-4fee9.appspot.com',
    iosBundleId: 'com.example.isspiBd3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KCOw2lAXKrS9LTw8VZrdYEWLH0yACmI',
    appId: '1:521390409536:ios:4dbe9e28de6a56b0f39ca5',
    messagingSenderId: '521390409536',
    projectId: 'ipssiflutter-4fee9',
    storageBucket: 'ipssiflutter-4fee9.appspot.com',
    iosBundleId: 'com.example.isspiBd3.RunnerTests',
  );
}
